<a href="https://colab.research.google.com/github/19PA1A0258/Al-Lab/blob/master/Experiment_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # Experiment 1 numpy

In [15]:
import numpy as np

## I) Different ways to create numpy array

 ### 1)create numpy using list

In [ ]:
r=np.array([5,6,7])
print(r)

[5 6 7]


In [ ]:
r=np.array([[3,4],[6,7],[8,9]])
print(r)

[[3 4]
 [6 7]
 [8 9]]


 ## II)Add, remove, modify elements in an array

 ### 1)Adding elements in array

In [ ]:
b=np.append([3,4,5,6],r)
print(b)

[3 4 5 6 3 4 6 7 8 9]


### 2)Remove elements in array

In [13]:
m=np.array([[1,2,7,9,8],[1,2,3,4,5]])
print(m)

[[1 2 7 9 8]
 [1 2 3 4 5]]


In [14]:
np.delete(m,1,0)

array([[1, 2, 7, 9, 8]])

### 3)modify elements in array

In [ ]:
x=np.array([[ 0.42436315, 0.48558583, 0.32924763], [ 0.7439979,0.58220701,0.38213418], [ 0.5097581,0.34528799,0.1563123 ]])
x[x>.5]=.5
print(x)

[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


 ## III)Arithmetic operations on NumPy array

In [ ]:
a=np.random.randint(100,size=5)
b=np.random.randint(100,size=5)
print(a)
print(b)

[69 35 19 45 36]
[62 32  8 29 56]


In [ ]:
sum=np.add(a,b)
pro=np.multiply(a,b)
sub=np.subtract(a,b)
div=np.divide(a,b)
mod=np.mod(a,b)
print(sum)
print(pro)
print(sub)
print(div)
print(mod)

[131  67  27  74  92]
[4278 1120  152 1305 2016]
[  7   3  11  16 -20]
[1.11290323 1.09375    2.375      1.55172414 0.64285714]
[ 7  3  3 16 36]


## IV)Slicing and iterating of NumPy arrays

### 1)slicing

In [3]:
a=np.array([1, 2, 3, 4, 5, 6, 7])
print(a[1:5])

[2 3 4 5]


In [5]:
 
b= np.array([1, 2, 3, 4, 5, 6, 7])
print(b[1:5:2])

[2 4]


 ### 2)iterating

In [6]:
a=np.array([[1, 2, 3], [4, 5, 6]])
for x in a:
  print(x)

[1 2 3]
[4 5 6]


In [7]:
b=np.array([1,2,3,4,5,6,7,8,9,10])
for x in b:
  print(x)

1
2
3
4
5
6
7
8
9
10


 ##  V)Matrix operations on NumPy arrays

In [8]:
x = np.array([1,5,2])
y = np.array([7,4,1])
Sum=np.add(x,y)
Sub=np.subtract(x,y)
Pro=np.multiply(x,y)
Div=np.divide(x,y)
print(x)
print(y)
print(Sum)
print(Sub)
print(Pro)
print(Div)

[1 5 2]
[7 4 1]
[8 9 3]
[-6  1  1]
[ 7 20  2]
[0.14285714 1.25       2.        ]
